Repository sonia-auv/proc_actuators, pull requests merged in 2020-07, with the labels that each got.

#11 Feature/dockerize project
  .github/ISSUE_TEMPLATE/bug_report_critical.md
  .github/ISSUE_TEMPLATE/bug_report_high.md
  .github/ISSUE_TEMPLATE/bug_report_low.md
  .github/ISSUE_TEMPLATE/bug_report_medium.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement_request_critical.md
  .github/ISSUE_TEMPLATE/enhancement_request_high.md
  .github/ISSUE_TEMPLATE/enhancement_request_low.md
  .github/ISSUE_TEMPLATE/enhancement_request_medium.md
  .github/ISSUE_TEMPLATE/feature_request_critical.md
  .github/ISSUE_TEMPLATE/feature_request_high.md
  .github/ISSUE_TEMPLATE/feature_request_low.md
  .github/ISSUE_TEMPLATE/feature_request_medium.md
  .github/pull_request_template.md
  .github/workflows/docker-image-robot-develop.yml
  .github/workflows/docker-image-robot-feature.yml
  .github/workflows/docker-image-robot-master.yml
  Dockerfile
  scripts/sonia_entrypoint.sh
Labels: Priority: High, Type: Feature

#13 Feature/add remote container dev
  .devcontainer/devcontainer.json
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/tasks.json
  Dockerfile
Labels: Priority: High, Type: Enhancement

#17 Develop
  .dockerignore
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-master.yml
  CMakeLists.txt
  Dockerfile
  package.xml
  src/proc_actuators/proc_actuators_node.cc
  src/proc_actuators/proc_actuators_node.h
Labels: Priority: High

#18 Fix workflow
  .github/workflows/docker-image-perception-master.yml
Labels: Priority: High
